version: "3.8"

services:

  tfrunner:  # Holds terraform code
    build:
      context: ./tfrunner/  # Build init
      dockerfile: ./Dockerfile
    container_name: tfrunner-cnt
    tty: true  # For running interacative programs & processes within the container
    volumes:
      - type: bind  # Connect directory from host to container
        source: ./terraform
        target: /mnt/terraform

  localstack:
    image: localstack/localstack:3.7.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,iam,apigateway,lambda,ec2 # Services to emulate
      - LAMBDA_EXECUTOR=docker-reuse # Uses same container for multiple lambda invocations
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=myrootaccesskeyid
      - AWS_SECRET_ACCESS_KEY=myrootsecretaccesskey
      - AWS_DEFAULT_REGION=eu-west-3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: "root"
    privileged: true
